# Generated by Django 4.1.1 on 2022-09-22 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('food_type', models.CharField(choices=[('F', 'Fruit'), ('V', 'Vegetable'), ('U', 'Unknown')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('friends', models.JSONField(blank=True, null=True)),
                ('has_died', models.BooleanField(blank=True, default=None, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('picture', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('eye_color', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('registered', models.DateTimeField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pandora.company')),
                ('favourite_food', models.ManyToManyField(to='pandora.food')),
                ('tags', models.ManyToManyField(to='pandora.tag')),
            ],
        ),
    ]
